import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { auth } from "@/server/auth";
import { TRPCReactProvider } from "@/trpc/react";
import { Suspense } from "react";
import { Dock } from "./_components/DockItem";
import Navbar from "./_components/Navbar";

export const metadata: Metadata = {
  title: {
    template: "%s | Datenschurz",
    default: "Datenschurz",
  },
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="de" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <Suspense
            fallback={
              <div className="navbar bg-base-100 skeleton shadow-sm"></div>
            }
          >
            <Navbar />
          </Suspense>
          {children}
          <Dock />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
