import "@/styles/globals.css";

import { env } from "@/env";
import { TRPCReactProvider } from "@/trpc/react";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { Suspense } from "react";
import { Dock } from "./_components/DockItem";
import Navbar from "./_components/Navbar";

export const metadata: Metadata = {
  title: {
    template: `%s | ${env.NEXT_PUBLIC_APP_NAME}`,
    default: env.NEXT_PUBLIC_APP_NAME,
  },
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="de" className={`${GeistSans.variable}`}>
      <body className="bg-base-200 text-base-content min-h-[100vh] antialiased">
        <TRPCReactProvider>
          <Suspense
            fallback={
              <div className="navbar bg-base-100 skeleton shadow-sm"></div>
            }
          >
            <Navbar />
          </Suspense>
          {children}
          <Dock />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
